# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-13 06:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('adminsideserviceprovider', '0001_initial'),
        ('adminsidecustomer', '0001_initial'),
        ('crmadmin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('questions', models.TextField(blank=True, help_text='Enter Details Name')),
                ('answers', models.TextField(blank=True, help_text='Enter Details Name')),
                ('docs', models.FileField(null=True, upload_to='static/faq_doc/')),
                ('link', models.CharField(help_text='Enter URL', max_length=255)),
                ('status', models.CharField(choices=[('active', 'active'), ('inactive', 'inactive'), ('delete', 'delete')], default='active', help_text='Enter Status', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Followus',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('url', models.TextField(blank=True, help_text='Enter Details Name')),
                ('fa_fa_icon', models.TextField(blank=True, help_text='Enter fa fa icon')),
                ('status', models.CharField(choices=[('active', 'active'), ('inactive', 'inactive'), ('delete', 'delete')], default='active', help_text='Enter Status', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='MenuCategory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('active', 'active'), ('inactive', 'inactive'), ('delete', 'delete')], default='active', help_text='Enter active status', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('service_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crmadmin.ManageServicesPriceCategory')),
            ],
        ),
        migrations.CreateModel(
            name='MenuParentCategory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('service_parent_category_name', models.CharField(help_text='Enter Parent Service Name', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='MenuSubParentCategory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('service_sub_parent_category_name', models.CharField(help_text='Enter Sub Parent Service Name', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('service_parent_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sitefrontendbyadmin.MenuParentCategory')),
            ],
        ),
        migrations.CreateModel(
            name='Network_status',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('questions', models.TextField(blank=True, help_text='Enter Details Name')),
                ('answers', models.TextField(blank=True, help_text='Enter Details Name')),
                ('docs', models.FileField(null=True, upload_to='static/network_status_doc/')),
                ('link', models.CharField(help_text='Enter URL', max_length=255)),
                ('status', models.CharField(choices=[('active', 'active'), ('inactive', 'inactive'), ('delete', 'delete')], default='active', help_text='Enter Status', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='serviceandfeature',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('details', models.CharField(help_text='Enter Details Name', max_length=255)),
                ('service_feature_logo', models.FileField(blank=True, upload_to='static/service_feature_logo/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('service_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crmadmin.ManageServicesPriceCategory')),
                ('service_parent_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sitefrontendbyadmin.MenuParentCategory')),
                ('service_sub_parent_category_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sitefrontendbyadmin.MenuSubParentCategory')),
            ],
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('slider_name', models.CharField(help_text='Enter Details Name', max_length=255)),
                ('details', models.TextField(blank=True, help_text='Enter Details Name')),
                ('image', models.FileField(blank=True, upload_to='static/slider_image/')),
                ('url', models.CharField(help_text='Enter URL', max_length=255)),
                ('status', models.CharField(choices=[('active', 'active'), ('inactive', 'inactive'), ('delete', 'delete')], default='active', help_text='Enter Status', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SpecialOffers',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('details', models.TextField(blank=True, help_text='Enter Details Name')),
                ('features', models.TextField(blank=True, help_text='Enter Features')),
                ('actual_price', models.CharField(blank=True, help_text='Enter Price', max_length=255)),
                ('offers_price', models.CharField(blank=True, help_text='Enter Price', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Specialoffersdoc',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('special_offers_doc_name', models.CharField(blank=True, help_text='Enter Special Offers DOC Name', max_length=255)),
                ('special_offers_doc', models.FileField(blank=True, upload_to='static/special_offers_doc/')),
                ('status', models.CharField(choices=[('active', 'active'), ('inactive', 'inactive'), ('delete', 'delete')], default='active', help_text='Enter Status', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('special_offers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sitefrontendbyadmin.SpecialOffers')),
            ],
        ),
        migrations.CreateModel(
            name='SpecialoffersParentCategory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('special_offers_parent_category_name', models.CharField(help_text='Enter Parent Service Name', max_length=255)),
                ('desc', models.TextField(blank=True, help_text='Enter Sub Parent Special Offers Description')),
                ('status', models.CharField(choices=[('active', 'active'), ('inactive', 'inactive'), ('delete', 'delete')], default='active', help_text='Enter active status', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SpecialOffersPlans',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('actual_price', models.CharField(blank=True, help_text='Enter Price', max_length=255)),
                ('offers_price', models.CharField(blank=True, help_text='Enter Price', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('service_price', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crmadmin.ManageServicePrice')),
                ('special_offers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sitefrontendbyadmin.SpecialOffers')),
            ],
        ),
        migrations.CreateModel(
            name='SpecialOffersPlansHardWare',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('actual_price', models.CharField(blank=True, help_text='Enter Price', max_length=255)),
                ('offers_price', models.CharField(blank=True, help_text='Enter Price', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('service_price', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crmadmin.ManageServicePrice')),
                ('special_offers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sitefrontendbyadmin.SpecialOffers')),
            ],
        ),
        migrations.CreateModel(
            name='SpecialOffersPlanswithHardwareRates',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('hw_qty', models.CharField(help_text='Enter Service Provider Plan Quantity', max_length=255)),
                ('device_buy', models.CharField(blank=True, help_text='Enter Device Buy', max_length=255)),
                ('device_rental', models.CharField(blank=True, help_text='Enter Device Rental', max_length=255)),
                ('montly_rent', models.CharField(blank=True, help_text='Enter Montly rent', max_length=255)),
                ('offer_price', models.CharField(blank=True, help_text='Enter Offer Price', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hw', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminsideserviceprovider.Hardware')),
                ('service_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminsideserviceprovider.ServiceProviderPlan')),
                ('service_price', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crmadmin.ManageServicePrice')),
                ('special_offers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sitefrontendbyadmin.SpecialOffers')),
            ],
        ),
        migrations.CreateModel(
            name='SpecialoffersSubParentCategory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('special_offers_sub_parent_category_name', models.CharField(help_text='Enter Sub Parent Special Offers Name', max_length=255)),
                ('desc', models.TextField(blank=True, help_text='Enter Sub Parent Special Offers Description')),
                ('status', models.CharField(choices=[('active', 'active'), ('inactive', 'inactive'), ('delete', 'delete')], default='active', help_text='Enter active status', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('special_offers_parent_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sitefrontendbyadmin.SpecialoffersParentCategory')),
            ],
        ),
        migrations.CreateModel(
            name='SpecialoffersUnderCategory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('special_offers_combo_name', models.CharField(blank=True, help_text='Enter Special Offers Combo Name', max_length=255)),
                ('special_offers_type_name', models.CharField(blank=True, help_text='Enter Special Offers Type Name', max_length=255)),
                ('telecom_name', models.CharField(blank=True, help_text='Enter Telecom Name', max_length=255)),
                ('telecom_logo', models.FileField(blank=True, upload_to='static/telecom_logo/')),
                ('status', models.CharField(choices=[('active', 'active'), ('inactive', 'inactive'), ('delete', 'delete')], default='active', help_text='Enter active status', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminsidecustomer.City')),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminsidecustomer.Province')),
                ('special_offers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sitefrontendbyadmin.SpecialOffers')),
                ('special_offers_parent_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sitefrontendbyadmin.SpecialoffersParentCategory')),
                ('special_offers_sub_parent_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sitefrontendbyadmin.SpecialoffersSubParentCategory')),
            ],
        ),
        migrations.CreateModel(
            name='WebLogo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.FileField(null=True, upload_to='static/web_logo/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='menucategory',
            name='service_parent_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sitefrontendbyadmin.MenuParentCategory'),
        ),
        migrations.AddField(
            model_name='menucategory',
            name='service_sub_parent_category_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sitefrontendbyadmin.MenuSubParentCategory'),
        ),
    ]
