# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-17 06:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitefrontendbyadmin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceandfeature',
            name='details',
            field=models.TextField(help_text='Enter Details Name', max_length=20000),
        ),
    ]
