# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-29 08:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitefrontendbyadmin', '0002_auto_20190717_0624'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuparentcategory',
            name='status',
            field=models.CharField(choices=[('active', 'active'), ('inactive', 'inactive'), ('delete', 'delete')], default='active', help_text='Enter active status', max_length=15),
        ),
        migrations.AddField(
            model_name='menusubparentcategory',
            name='status',
            field=models.CharField(choices=[('active', 'active'), ('inactive', 'inactive'), ('delete', 'delete')], default='active', help_text='Enter active status', max_length=15),
        ),
        migrations.AddField(
            model_name='serviceandfeature',
            name='status',
            field=models.CharField(choices=[('active', 'active'), ('inactive', 'inactive'), ('delete', 'delete')], default='active', help_text='Enter active status', max_length=15),
        ),
    ]
