# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-13 06:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('adminsidecustomer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ratewithareacode',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('area_code', models.CharField(help_text='Enter area code', max_length=255)),
                ('rate', models.FloatField(help_text='Enter rate', max_length=255)),
                ('status', models.CharField(choices=[('True', 'True'), ('False', 'False')], default='True', help_text='Enter Status', max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminsidecustomer.Country')),
                ('province', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='adminsidecustomer.Province')),
            ],
        ),
    ]
