# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-01 09:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminsideserviceprovider', '0007_auto_20191001_0622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerservicecontract',
            name='type',
            field=models.CharField(choices=[('New', 'New'), ('Renew', 'Renew'), ('Terminate', 'Terminate')], default='New', help_text='Enter Type', max_length=150),
        ),
    ]
