# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-11-13 10:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminsideserviceprovider', '0009_auto_20191001_1412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerservicecontract',
            name='type',
            field=models.CharField(choices=[('Terminate', 'Terminate'), ('Renew', 'Renew'), ('New', 'New')], default='New', help_text='Enter Type', max_length=150),
        ),
    ]
