# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-11-14 08:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminsideserviceprovider', '0011_auto_20191113_1114'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerticketscategoriesmap',
            name='service_plan_hardware',
        ),
        migrations.RemoveField(
            model_name='customerticketscategoriesmap',
            name='service_provider',
        ),
        migrations.AlterField(
            model_name='customerservicecontract',
            name='type',
            field=models.CharField(choices=[('Terminate', 'Terminate'), ('New', 'New'), ('Renew', 'Renew')], default='New', help_text='Enter Type', max_length=150),
        ),
    ]
