# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-13 06:38
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerBillingDetails',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('customer_service_contract', models.TextField(help_text='Enter Contract')),
                ('call_cost', models.TextField(help_text='Enter Call Cost')),
                ('previous_balance', models.TextField(help_text='Enter Previous Balance')),
                ('current_balance', models.TextField(help_text='Enter Current Balance')),
                ('due_amount', models.TextField(help_text='Enter Due Amount')),
                ('payment_status', models.CharField(choices=[('Pending', 'Pending'), ('Complete', 'Complete'), ('Fail', 'Fail')], default='Pending', help_text='Enter active payment status', max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerBillingDetailsWithEdited',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('reduce_payment', models.TextField(help_text='Enter Reduce Amount')),
                ('paid_payment', models.TextField(help_text='Enter Paid Amount')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer_billing_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ratecustomerbillingwithcdr.CustomerBillingDetails')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VoipLongDistanceRate',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('country', models.CharField(blank=True, help_text='Enter Country', max_length=255, null=True)),
                ('prefix', models.CharField(blank=True, help_text='Enter Prefix', max_length=255, null=True)),
                ('rate', models.CharField(blank=True, help_text='Enter Rate', max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
