# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-13 06:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('adminsidecustomer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NumberMNPtoCustomer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('number', models.BigIntegerField()),
                ('approve_upload_data', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminsidecustomer.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='NumberProvinceCustomerMap',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='NumberProvinceMap',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('did_id', models.CharField(help_text='Enter Did id ', max_length=255)),
                ('npa', models.CharField(help_text='Enter NPA', max_length=255)),
                ('nxx', models.CharField(help_text='Enter NXX', max_length=255)),
                ('xxxx', models.CharField(help_text='Enter XXXX', max_length=255)),
                ('tier', models.CharField(help_text='Enter TIER', max_length=255)),
                ('ratecenters', models.CharField(help_text='Enter Ratecenter', max_length=255)),
                ('number', models.CharField(help_text='Enter number', max_length=255)),
                ('setup_rate', models.CharField(help_text='Enter set up rate', max_length=255)),
                ('monthly_rate', models.CharField(help_text='Enter monthly rate', max_length=255)),
                ('per_minute_rate', models.CharField(help_text='Enter per minitue rate', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminsidecustomer.Country')),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminsidecustomer.Province')),
            ],
        ),
        migrations.AddField(
            model_name='numberprovincecustomermap',
            name='number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminnumberprovider.NumberProvinceMap'),
        ),
        migrations.AddField(
            model_name='numberprovincecustomermap',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminsidecustomer.Customer'),
        ),
    ]
