# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-11-18 10:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crmadmin', '0001_initial'),
        ('adminsidecustomer', '0014_auto_20191118_1012'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingDetailsCustomer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('contract_type', models.CharField(help_text='Enter Contract Type', max_length=255)),
                ('billing_day', models.CharField(help_text='Enter Billing Day', max_length=255)),
                ('payment_mode', models.CharField(help_text='Enter Payment Mode', max_length=255)),
                ('payment_method', models.CharField(help_text='Enter Payment Method', max_length=255)),
                ('year_pre_payment', models.CharField(blank=True, help_text='Enter Year Pre Payment', max_length=255, null=True)),
                ('billing_from', models.CharField(help_text='Enter Billing From', max_length=255)),
                ('billing_to', models.CharField(help_text='Enter Billing To', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('salesperson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crmadmin.UserProfile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminsidecustomer.Customer')),
            ],
        ),
    ]
