# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-13 06:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('adminsideserviceprovider', '0001_initial'),
        ('adminsidecustomer', '0001_initial'),
        ('sitefrontendbyadmin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerApplyForService',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(help_text='Enter First Name', max_length=255)),
                ('last_name', models.CharField(help_text='Enter First Name', max_length=255)),
                ('email_address', models.CharField(help_text='Enter Email Address', max_length=255)),
                ('company_name', models.CharField(help_text='Enter Company Name', max_length=255)),
                ('phone', models.BigIntegerField()),
                ('cell_number', models.BigIntegerField()),
                ('call_time', models.CharField(help_text='Enter Call Time', max_length=255)),
                ('installation_time', models.CharField(help_text='Enter Installation Time', max_length=255)),
                ('hear_about_us', models.CharField(help_text='Enter Hear About Us', max_length=255)),
                ('existing_service_provider', models.CharField(help_text='Enter Service Provider', max_length=255)),
                ('service_date_time', models.CharField(help_text='Enter Service Date Time', max_length=255)),
                ('cancellation_date_with_current_provider', models.CharField(help_text='Enter Cancellation Date With Current Provider', max_length=255)),
                ('terms_of_service', models.CharField(help_text='Enter Terms of Service', max_length=255)),
                ('referred_ac_no', models.CharField(help_text='Enter Referred Account No', max_length=255)),
                ('referred_by', models.CharField(help_text='Enter Referred By', max_length=255)),
                ('promo_code', models.CharField(help_text='Enter Promo Code', max_length=255)),
                ('message', models.TextField(blank=True, help_text='Enter Message')),
                ('service_address_1', models.CharField(help_text='Enter Service Street Number 1', max_length=255)),
                ('service_address_2', models.CharField(help_text='Enter Service Street Number 2', max_length=255)),
                ('service_apt_suite', models.CharField(help_text='Enter Service Apt./Suite', max_length=255)),
                ('service_postcode', models.CharField(help_text='Enter Service Postal Code', max_length=255)),
                ('applied_ip_address', models.CharField(blank=True, help_text='Enter Ip Address', max_length=255)),
                ('previous_invoice', models.FileField(blank=True, null=True, upload_to='static/previous_invoice/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('menu_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sitefrontendbyadmin.MenuCategory')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminsideserviceprovider.ServiceProviderPlan')),
                ('service_city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminsidecustomer.City')),
                ('service_country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminsidecustomer.Country')),
                ('service_province', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminsidecustomer.Province')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerApplyForServiceBilling',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('billing_address_1', models.CharField(help_text='Enter Billing Street Number 1', max_length=255)),
                ('billing_address_2', models.CharField(help_text='Enter Billing Street Number 2', max_length=255)),
                ('billing_apt_suite', models.CharField(help_text='Enter Billing Apt./Suite', max_length=255)),
                ('billing_postcode', models.CharField(help_text='Enter Billing Postal Code', max_length=255)),
                ('billing_city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminsidecustomer.City')),
                ('billing_country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminsidecustomer.Country')),
                ('billing_province', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminsidecustomer.Province')),
                ('customer_apply_for_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='egciptvhome.CustomerApplyForService')),
            ],
        ),
        migrations.CreateModel(
            name='Otherdetails',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('key', models.CharField(help_text='Enter key', max_length=255)),
                ('value', models.TextField(blank=True, help_text='Enter Value', max_length=255)),
                ('address', models.CharField(blank=True, help_text='Enter Address', max_length=255)),
                ('city', models.CharField(blank=True, help_text='Enter City', max_length=255)),
                ('province', models.CharField(blank=True, help_text='Enter Province', max_length=255)),
                ('country', models.CharField(blank=True, help_text='Enter Country', max_length=255)),
                ('zip', models.CharField(blank=True, help_text='Enter Zip', max_length=255)),
                ('fax', models.CharField(blank=True, help_text='Enter Fax', max_length=255)),
                ('phone', models.CharField(blank=True, help_text='Enter Phone', max_length=255)),
                ('email', models.CharField(blank=True, help_text='Enter Email', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
