# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-01 09:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('egciptvhome', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerapplyforservice',
            name='call_time',
            field=models.CharField(blank=True, help_text='Enter Call Time', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='customerapplyforservice',
            name='cancellation_date_with_current_provider',
            field=models.CharField(blank=True, help_text='Enter Cancellation Date With Current Provider', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='customerapplyforservice',
            name='existing_service_provider',
            field=models.CharField(blank=True, help_text='Enter Service Provider', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='customerapplyforservice',
            name='hear_about_us',
            field=models.CharField(blank=True, help_text='Enter Hear About Us', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='customerapplyforservice',
            name='installation_time',
            field=models.CharField(blank=True, help_text='Enter Installation Time', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='customerapplyforservice',
            name='promo_code',
            field=models.CharField(blank=True, help_text='Enter Promo Code', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='customerapplyforservice',
            name='referred_ac_no',
            field=models.CharField(blank=True, help_text='Enter Referred Account No', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='customerapplyforservice',
            name='referred_by',
            field=models.CharField(blank=True, help_text='Enter Referred By', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='customerapplyforservice',
            name='service_date_time',
            field=models.CharField(blank=True, help_text='Enter Service Date Time', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='customerapplyforservice',
            name='terms_of_service',
            field=models.CharField(blank=True, help_text='Enter Terms of Service', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='customerapplyforservicebilling',
            name='billing_address_1',
            field=models.CharField(blank=True, help_text='Enter Billing Street Number 1', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='customerapplyforservicebilling',
            name='billing_address_2',
            field=models.CharField(blank=True, help_text='Enter Billing Street Number 2', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='customerapplyforservicebilling',
            name='billing_apt_suite',
            field=models.CharField(blank=True, help_text='Enter Billing Apt./Suite', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='customerapplyforservicebilling',
            name='billing_city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adminsidecustomer.City'),
        ),
        migrations.AlterField(
            model_name='customerapplyforservicebilling',
            name='billing_country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adminsidecustomer.Country'),
        ),
        migrations.AlterField(
            model_name='customerapplyforservicebilling',
            name='billing_postcode',
            field=models.CharField(blank=True, help_text='Enter Billing Postal Code', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='customerapplyforservicebilling',
            name='billing_province',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adminsidecustomer.Province'),
        ),
    ]
