# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-01 14:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('egciptvhome', '0002_auto_20191001_0913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerapplyforservice',
            name='company_name',
            field=models.CharField(blank=True, help_text='Enter Company Name', max_length=255, null=True),
        ),
    ]
