# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-13 06:38
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractSheet',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title1', models.TextField(blank=True, help_text='Enter Title 1')),
                ('title2', models.TextField(blank=True, help_text='Enter Title 2')),
                ('title3', models.TextField(blank=True, help_text='Enter Title 3')),
                ('title4', models.TextField(blank=True, help_text='Enter Title 4')),
                ('title5', models.TextField(blank=True, help_text='Enter Title 5')),
                ('title6', models.TextField(blank=True, help_text='Enter Title 6')),
                ('title7', models.TextField(blank=True, help_text='Enter Title 7')),
                ('title8', models.TextField(blank=True, help_text='Enter Title 8')),
                ('title9', models.TextField(blank=True, help_text='Enter Title 9')),
                ('title10', models.TextField(blank=True, help_text='Enter Title 10')),
                ('title11', models.TextField(blank=True, help_text='Enter Title 11')),
                ('title12', models.TextField(blank=True, help_text='Enter Title 12')),
                ('title13', models.TextField(blank=True, help_text='Enter Title 13')),
                ('title14', models.TextField(blank=True, help_text='Enter Title 14')),
                ('title15', models.TextField(blank=True, help_text='Enter Title 15')),
                ('title16', models.TextField(blank=True, help_text='Enter Title 16')),
                ('title17', models.TextField(blank=True, help_text='Enter Title 17')),
                ('title18', models.TextField(blank=True, help_text='Enter Title 18')),
                ('title19', models.TextField(blank=True, help_text='Enter Title 19')),
                ('title20', models.TextField(blank=True, help_text='Enter Title 20')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
