# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-13 06:39
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(help_text='Enter First Name', max_length=255)),
                ('last_name', models.CharField(help_text='Enter Last Name', max_length=255)),
                ('email_address', models.CharField(help_text='Enter Email Address', max_length=255)),
                ('phone', models.BigIntegerField()),
                ('status', models.CharField(choices=[('Agent', 'Agent')], default='Agent', help_text='Enter Status', max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
