# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-13 06:38
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crmadmin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountAddressCustomer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('address_1', models.CharField(help_text='Enter Address 1', max_length=255)),
                ('address_2', models.CharField(help_text='Enter Address 2', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='BillingAddressCustomer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('billing_address_1', models.CharField(help_text='Enter Billing Address 1', max_length=255)),
                ('billing_address_2', models.CharField(help_text='Enter Billing Address 2', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='BillingDetailsCustomer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('contract_type', models.CharField(help_text='Enter Contract Type', max_length=255)),
                ('billing_day', models.CharField(help_text='Enter Billing Day', max_length=255)),
                ('payment_mode', models.CharField(help_text='Enter Payment Mode', max_length=255)),
                ('payment_method', models.CharField(help_text='Enter Payment Method', max_length=255)),
                ('year_pre_payment', models.CharField(help_text='Enter Year Pre Payment', max_length=255)),
                ('billing_from', models.CharField(help_text='Enter Billing From', max_length=255)),
                ('billing_to', models.CharField(help_text='Enter Billing To', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('salesperson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crmadmin.UserProfile')),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('city_name', models.CharField(help_text='Enter City Name', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('country_name', models.CharField(help_text='Enter Country Name', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('account_id', models.CharField(help_text='Enter Account Id', max_length=255)),
                ('status', models.CharField(help_text='Enter Status', max_length=255)),
                ('first_name', models.CharField(help_text='Enter First Name', max_length=255)),
                ('first_name_gsr', models.CharField(help_text='Enter GSR', max_length=255)),
                ('last_name', models.CharField(help_text='Enter First Name', max_length=255)),
                ('last_name_gsr', models.CharField(help_text='Enter GSR', max_length=255)),
                ('company_name', models.CharField(help_text='Enter Company Name', max_length=255)),
                ('company_name_gsr', models.CharField(help_text='Enter GSR', max_length=255)),
                ('email_address', models.CharField(help_text='Enter Email Address', max_length=255)),
                ('phone', models.BigIntegerField()),
                ('other_phone', models.BigIntegerField()),
                ('portal_password', models.CharField(help_text='Enter Portal Password', max_length=255)),
                ('dob', models.CharField(help_text='Enter Date Of Birth', max_length=255)),
                ('display_name', models.CharField(choices=[('user_name', 'user_name'), ('company_name', 'company_name')], default='user_name', help_text='Enter active status', max_length=150)),
                ('prefferd_language', models.CharField(choices=[('english', 'english'), ('french', 'french')], default='english', help_text='Enter active status', max_length=150)),
                ('zone', models.CharField(choices=[('commercial', 'commercial'), ('residential', 'residential')], default='commercial', help_text='Enter active zone', max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerAccountStatus',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('contract_sent', models.CharField(choices=[('True', 'True'), ('False', 'False')], default='False', help_text='Enter Contract Sent', max_length=150)),
                ('contract_accepted', models.CharField(choices=[('True', 'True'), ('False', 'False')], default='False', help_text='Enter Contract Accepted', max_length=150)),
                ('first_payment_done', models.CharField(choices=[('True', 'True'), ('False', 'False')], default='False', help_text='Enter First Payment Done', max_length=150)),
                ('req_has_been_sent', models.CharField(choices=[('True', 'True'), ('False', 'False')], default='False', help_text='Enter Req has been sent', max_length=150)),
                ('devices_shipped', models.CharField(choices=[('True', 'True'), ('False', 'False')], default='False', help_text='Enter Devices Shipped ', max_length=150)),
                ('devices_received', models.CharField(choices=[('True', 'True'), ('False', 'False')], default='False', help_text='Enter Devices Received ', max_length=150)),
                ('installation_date', models.CharField(choices=[('True', 'True'), ('False', 'False')], default='False', help_text='Enter Installation Date', max_length=150)),
                ('installation_done', models.CharField(choices=[('True', 'True'), ('False', 'False')], default='False', help_text='Enter Installation Done', max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminsidecustomer.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerComment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('comment', models.TextField(help_text='Enter Comment')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('touser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='touser', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerInvoiceMap',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('details', models.TextField(help_text='Enter Detils')),
                ('invoice_month', models.TextField(help_text='Enter Invoive Month')),
                ('amount_type', models.CharField(choices=[('Debit', 'Debit'), ('Credit', 'Credit'), ('Late Payemt Free Credit', 'Late Payemt Free Credit'), ('Late Payemt Free Debit', 'Late Payemt Free Debit')], default='Debit', help_text='Enter Category', max_length=150)),
                ('end_term', models.CharField(choices=[('True', 'T'), ('False', 'F')], default='T', help_text='Enter End Term', max_length=150)),
                ('status', models.CharField(choices=[('Paid', 'Paid'), ('Pending', 'Pending')], default='Pending', help_text='Enter Status', max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminsidecustomer.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerUserMap',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminsidecustomer.Customer')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CutomerAttachmentMap',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('file_name', models.TextField(help_text='Enter File Name ')),
                ('filedata', models.FileField(upload_to='static/attachments/')),
                ('file_type', models.TextField(help_text='Enter File Type ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminsidecustomer.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('province_name', models.CharField(help_text='Enter Province Name', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('country_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminsidecustomer.Country')),
            ],
        ),
        migrations.CreateModel(
            name='Sales_tax',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tax_name', models.CharField(help_text='Enter Province Name', max_length=255)),
                ('abbreviation', models.CharField(help_text='Enter Province Name', max_length=255)),
                ('description', models.TextField(help_text='Enter Province Name')),
                ('tax_number', models.BigIntegerField()),
                ('is_tax_number_show', models.CharField(choices=[('True', 'True'), ('False', 'False')], default='False', help_text='Enter Tax Number Show', max_length=150)),
                ('is_fedral_tax', models.CharField(choices=[('True', 'True'), ('False', 'False')], default='False', help_text='Enter Fedral Tax', max_length=150)),
                ('is_provisional_tax', models.CharField(choices=[('True', 'True'), ('False', 'False')], default='False', help_text='Enter Provisional Tax', max_length=150)),
                ('tax_rate', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminsidecustomer.Province')),
            ],
        ),
        migrations.AddField(
            model_name='city',
            name='province_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminsidecustomer.Province'),
        ),
        migrations.AddField(
            model_name='billingdetailscustomer',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminsidecustomer.Customer'),
        ),
        migrations.AddField(
            model_name='billingaddresscustomer',
            name='billing_city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminsidecustomer.City'),
        ),
        migrations.AddField(
            model_name='billingaddresscustomer',
            name='billing_country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminsidecustomer.Country'),
        ),
        migrations.AddField(
            model_name='billingaddresscustomer',
            name='billing_province',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminsidecustomer.Province'),
        ),
        migrations.AddField(
            model_name='billingaddresscustomer',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminsidecustomer.Customer'),
        ),
        migrations.AddField(
            model_name='accountaddresscustomer',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminsidecustomer.City'),
        ),
        migrations.AddField(
            model_name='accountaddresscustomer',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminsidecustomer.Country'),
        ),
        migrations.AddField(
            model_name='accountaddresscustomer',
            name='province',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminsidecustomer.Province'),
        ),
        migrations.AddField(
            model_name='accountaddresscustomer',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminsidecustomer.Customer'),
        ),
    ]
