# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-13 07:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminsidecustomer', '0002_auto_20190713_0639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerinvoicemap',
            name='end_term',
            field=models.CharField(choices=[('True', 'T'), ('False', 'F')], default='T', help_text='Enter End Term', max_length=150),
        ),
        migrations.AlterField(
            model_name='customerinvoicemap',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Paid', 'Paid')], default='Pending', help_text='Enter Status', max_length=150),
        ),
    ]
