# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-17 06:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminsidecustomer', '0003_auto_20190713_0702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerinvoicemap',
            name='end_term',
            field=models.CharField(choices=[('False', 'F'), ('True', 'T')], default='T', help_text='Enter End Term', max_length=150),
        ),
    ]
