# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-11-12 11:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminsidecustomer', '0009_auto_20191001_1412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerinvoicemap',
            name='status',
            field=models.CharField(choices=[('Paid', 'Paid'), ('Pending', 'Pending')], default='Pending', help_text='Enter Status', max_length=150),
        ),
    ]
