# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-11-13 10:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminsidecustomer', '0010_auto_20191112_1112'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountaddresscustomer',
            name='postal',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='billingaddresscustomer',
            name='postal',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='company_name',
            field=models.CharField(blank=True, help_text='Enter Company Name', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='customerinvoicemap',
            name='end_term',
            field=models.CharField(choices=[('True', 'T'), ('False', 'F')], default='T', help_text='Enter End Term', max_length=150),
        ),
    ]
