# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-11-13 11:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminsidecustomer', '0011_auto_20191113_1019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerinvoicemap',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Paid', 'Paid')], default='Pending', help_text='Enter Status', max_length=150),
        ),
    ]
