# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-11-18 10:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminsidecustomer', '0013_auto_20191114_0803'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billingdetailscustomer',
            name='salesperson',
        ),
        migrations.RemoveField(
            model_name='billingdetailscustomer',
            name='user',
        ),
        migrations.AlterField(
            model_name='customerinvoicemap',
            name='end_term',
            field=models.CharField(choices=[('True', 'T'), ('False', 'F')], default='T', help_text='Enter End Term', max_length=150),
        ),
        migrations.AlterField(
            model_name='customerinvoicemap',
            name='status',
            field=models.CharField(choices=[('Paid', 'Paid'), ('Pending', 'Pending')], default='Pending', help_text='Enter Status', max_length=150),
        ),
        migrations.DeleteModel(
            name='BillingDetailsCustomer',
        ),
    ]
