# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-11-18 11:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminsidecustomer', '0014_auto_20191118_1012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerinvoicemap',
            name='end_term',
            field=models.CharField(choices=[('False', 'F'), ('True', 'T')], default='T', help_text='Enter End Term', max_length=150),
        ),
    ]
