# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-13 06:38
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CallCost',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('source', models.CharField(help_text='Enter Service Name', max_length=255)),
                ('destination', models.CharField(help_text='Enter Service Name', max_length=255)),
                ('call_cost', models.CharField(help_text='Enter Call Cost', max_length=255)),
                ('start_date', models.CharField(help_text='Enter Start Date', max_length=255)),
                ('end_date', models.CharField(help_text='Enter End Date', max_length=255)),
                ('status', models.CharField(choices=[('if_user_number_source', 'if_user_number_source'), ('if_user_number_destination', 'if_user_number_destination')], default='if_user_number_source', help_text='Enter Status Type', max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ManageServicePrice',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('service_name', models.CharField(help_text='Enter Service Name', max_length=255)),
                ('service_price', models.FloatField(help_text='Enter Service Price')),
                ('service_desc', models.TextField(blank=True, help_text='Enter Service Description', max_length=15000)),
                ('service_logo', models.FileField(blank=True, upload_to='static/service_logo/')),
                ('status', models.CharField(choices=[('active', 'active'), ('inactive', 'inactive'), ('delete', 'delete')], default='active', help_text='Enter Active Status', max_length=15)),
                ('special_offer', models.CharField(blank=True, help_text='Enter Special offer', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ManageServicesPriceCategory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('service_category_name', models.CharField(help_text='Enter Service Name', max_length=255)),
                ('status', models.CharField(choices=[('active', 'active'), ('inactive', 'inactive'), ('delete', 'delete')], default='active', help_text='Enter active status', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='Enter Service Name', max_length=255)),
                ('price', models.FloatField(help_text='Enter Service Price')),
                ('phone_service', models.BooleanField(default=False)),
                ('internet_service', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserImage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('avatardata', models.FileField(upload_to='static/avatar/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('login_type', models.CharField(choices=[('salesperson', 'Salesperson'), ('support', 'Support'), ('administrator', 'Administrator')], default='salesperson', help_text='Enter Login Type', max_length=50)),
                ('commissions_in_USD', models.FloatField(help_text='Enter Commissions in $')),
                ('commissions_in_percent', models.FloatField(help_text='Enter Commissions in %')),
                ('role', models.CharField(choices=[('restricted', 'Restricted'), ('relaxed', 'Relaxed')], default='restricted', help_text='Enter Role Type', max_length=50)),
                ('extentions', models.CharField(help_text='Enter Extentions', max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='manageserviceprice',
            name='service_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crmadmin.ManageServicesPriceCategory'),
        ),
    ]
